### PR TITLE
Creating sq.js for the Albanian language

### PR DESCRIPTION
**Pull request by alensaqe**
Under ISO standards Albanian two letter code is 'sq'

### CODE REVIEW

**Comment by arshaw** [comment]
thanks

**Comment by alensaqe** [comment]
One question. Is locale-all.js auto generated? 

As it seems way more complicated from what i just translated i know you use moment.js localization for that matter.

For now i added more data into our local sq.js file, so it properly displays some more translation sets like months/weekdays etc.

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

**Comment by alensaqe** [comment]
That's great. Have a nice day!

**Pull request merged**
