### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by arshaw** [comment]
thank you!

could you also remove bower.json from `bump`?
https://github.com/fullcalendar/fullcalendar/blob/87d9ed4e6f65a8d3a8ecfad8c2ac888c2bd25418/Gruntfile.js#L307

**Comment by kkirsche** [comment]
Sadly I cannot. As this was one year ago, I've since deleted the fork assuming the project didn't care and was ignoring me.

**Comment by arshaw** [comment]
alright. ill do it

**Comment by arshaw** [comment]
[Code complete](https://github.com/fullcalendar/fullcalendar/commits/v2.8.0-dev) and slated for v2.8.0 ([wip docs](https://github.com/fullcalendar/fullcalendar/commits/docs-2.0)). Will notify when released.

**Pull request closed without merging**
