### PR TITLE
Add support for double clicking day slots

### PR DESCRIPTION
**Pull request by Ndpnt**
Double click events are fired only on calendar events. This changeset provides a `dayDoubleClick` event to listen to, just like `dayClick` does.

feature request ticket: #638 (for both events and day slots)

### CODE REVIEW

**Comment by atesoglu** [comment]
Hello,

Yes, dayRender could be an option for month, basicWeek and basicDay views but it is not working on agendaVeek views.

So how could we achieve attaching a dblclick event directly to a cell in agendaVeek views?

**Comment by arshaw** [comment]
it'd be convenient if this was built-in and wounldn't require much extra code anyway

**Comment by arshaw** [comment]
Apologies for the embarrassingly long wait time on this. Unfortunately the code has changed quite a bit since the time of this implementation. I'd recommend using the following technique

1. register the dblclick event [here](https://github.com/fullcalendar/fullcalendar/blob/v2.7.3/src/common/Grid.js#L176-L177)
2. don't use the `HitDragListener` like `dayMousedown ` and `dayTouchStart`,
3. instead, call the `Grid::queryHit` method to get a "hit area"
4. thread this into `getHitSpan` [like this](https://github.com/fullcalendar/fullcalendar/blob/v2.7.3/src/common/Grid.js#L332-L336) to get the date information to fire off to the dblclick handler

**Comment by arshaw** [comment]
Also, before considering a merge, would need automated tests for this, in Month/Basic/Agenda views.

If someone wants to pick this up, great. If not, this will remain in the standard feature-request queue.

**Comment by arshaw** [comment]
please let me know if you need help writing tests!
https://github.com/fullcalendar/fullcalendar/wiki/Automated-Tests
https://github.com/fullcalendar/fullcalendar/tree/master/tests/automated

**Comment by arshaw** [comment]
closing until we get some automated tests

**Pull request closed without merging**
