### PR TITLE
Added eventAfterRenderPopover and eventAfterAllRenderPopover events

### PR DESCRIPTION
**Pull request by Braunson**
Thanks all goes to Daniele Mammarella (@danielemams) for the code! Since they had no PR for this, I've created one and updated the original issue https://github.com/fullcalendar/fullcalendar/issues/2973

### CODE REVIEW

**Comment by danielemams** [comment]
well done.
im new on github, so i dont know how to request a git push of a commit.
thanks for like my code. hope it will help someone else like you!
danielemams.

**Comment by Braunson** [comment]
Thank you @danielbsig :+1: 

In the future you can create a pull request by Forking the primary repo to your own, making your changes and then creating a PR back to the primary repo for the owner (in this case @fullcalendar) to review :)

**Comment by danielemams** [comment]
good. this pull request was open by you. so its ok or i have to do something else?

**Comment by Braunson** [comment]
@danielemams It was opened to me, you don't have to do anything else, we are just waiting for the owner of @fullcalendar to merge it in :smile:

**Comment by arshaw** [comment]
Hello @Braunson and @danielemams thanks for the PR.

I'm want to propose some API changes here before merging this:

1. instead of introducing `eventAfterRenderPopover`, I'd rather user the existing `eventAfterRender` handler, but with an additional option passed in indicating that the event was rendered within a popover. Were you able to figure out if the standard `eventAfterRender` is already executed for events within a popover?

2. i understand the need for `eventAfterAllRenderPopover`, but I'd like to rename it to `eventAfterAllPopoverRender` to line up a little bit better with eventAfterAllRender

what do you think?

**Comment by danielemams** [comment]
Hi @arshaw,
'1' question: i think that the same function, with a parameter is better, yes. i don't understand what do you mean for "Were you able to figure out if the standard eventAfterRender is already executed for events within a popover?" ?
'2' question: ok, no problem for the name of the function.

Thanks for accept the pull request. :)

**Comment by Braunson** [comment]
@arshaw Both sound good! :+1:

**Comment by danielemams** [comment]
You'll find another pull request with the discussed changes: #3201

**Comment by arshaw** [comment]
i'll close this PR in favor of #3201, but please let me know if that's not the case and you'd like to resume development on here

**Comment by danielemams** [comment]
its ok. the pull request good is the #3201.

**Pull request closed without merging**
