### PR TITLE
fix(locale/de): restore ie11 support

### PR DESCRIPTION
**Pull request by BC-M**
According to https://fullcalendar.io/getting-help FullCalendar supports IE11, which be bricked by the de locales.

### CODE REVIEW

**Comment by acerix** [comment]
Please submit a ticket under Issues with a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/), then link this PR to it.

**Comment by BC-M** [comment]
[ES6 - Enhanced object literals](https://github.com/lukehoban/es6features#enhanced-object-literals) aren't implemented by IE11. 

Source: http://kangax.github.io/compat-table/es6/#test-object_literal_extensions

**Comment by BC-M** [comment]
You already resolved the same issue here: #6014.

**Comment by BC-M** [comment]
I will create a more detailed ticket after my vacation.

**Pull request closed without merging**
