### PR TITLE
Expose resource and timeslot on right click

### LINKED ISSUE #2748: Right-click on date cells
Originally reported on Google Code with ID 2483

```
I need the ability to let the user _right-click_ on a blank calendar-cell in “agendaWeek”
view and get the date/time returned into a JS variable.  

As an example of this not working, I have put this demo together:  https://jsfiddle.net/gouldtv/1j01ztdm/

Left-click works without issue.  It's just right-clicking in agenda-view that appears
to be impossible right nwo.
```

Reported by `gouldtv` on 2015-04-15 06:18:56

Imported with **1** stars.

### PR DESCRIPTION
**Pull request by bwobbones**
A test for the exposure of the resource and timeslot for a right click.

Closes #2748

### CODE REVIEW

**Comment by bwobbones** [comment]
Any idea what I've done wrong here?  I pushed some tests into the fullcalendar-scheduler repo, then pushed this one.  Looks like I have a reference to 5.4.0 somewhere still?

```
$ yarn install
➤ YN0000: ┌ Resolution step
Resolution
➤ ]8;;https://yarnpkg.com/advanced/error-codes#yn0001---exceptionYN0001]8;;: │ Error: @fullcalendar/core@workspace:~5.4.0: Workspace not found (@fullcalendar/core@workspace:~5.4.0)
    at Ae.getWorkspaceByDescriptor (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:331346)
    at i.getCandidates (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:376979)
    at i.getCandidates (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:314232)
    at i.getCandidates (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:314232)
    at /home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:335605
    at Array.map (<anonymous>)
    at Ae.resolveEverything (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:335321)
    at async /home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:353796
    at async C.startTimerPromise (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:364724)
    at async Ae.install (/home/travis/build/fullcalendar/fullcalendar/.yarn/releases/yarn-2.3.3.cjs:2:353430)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 170ms
```

**Comment by bwobbones** [comment]
Closing, will try again.

**Review by melloware — APPROVED** [review]

**Comment by bwobbones** [comment]
@acerix @arshaw any timeline on the next release?

**Comment by bwobbones** [comment]
@acerix @arshaw I see that this one wasn't merged for the recent release, is there something I can to do to make it easier for you?

**Comment by merry-ma-18** [comment]
Hi. This is very helpful and I hope this will be officially integrated soon. Meanwhile I use the intermediate npm version. Any chance to get this for eventClick as well please?

**Comment by melloware** [comment]
@bwobbones  looks like you need to rebase this PR there are merge conflicts.

**Comment by bwobbones** [comment]
Yes, I'll take care of that ASAP

**Comment by bwobbones** [comment]
@melloware fixed

**Comment by bwobbones** [comment]
Link to the tests: https://github.com/fullcalendar/fullcalendar-scheduler/pull/571
Link to the monkey patch: https://github.com/bwobbones/fullcalendar5-rightclick

**Comment by bwobbones** [comment]
@merry-ma-18 lets keep this PR clean, i'll have a look into a new PR for `eventClick`.

**Comment by bwobbones** [comment]
Can someone point me at some docs for managing the submodules here?  It seems that I get a conflict with the underlying packages-premium every time I update it.

**Comment by RafaelGreen1** [comment]
any update on this issue?

**Comment by RafaelGreen1** [comment]
@bwobbones it seems like you are changing these files: "packages-premium" and "yarn.lock" in this pull request
is it really your intention to change these files?

**Comment by RafaelGreen1** [comment]
@bwobbones maybe if you pull again, then applying your changes and run the things needed, the conflict might be solved, have tried it?

**Comment by RafaelGreen1** [comment]
@bwobbones this might help you: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by bwobbones** [comment]
For my own future reference, accepting incoming for `yarn.lock` running this command `git checkout master packages-premium` fixed it.

**Comment by bwobbones** [comment]
@acerix @arshaw please merge or let me know you won't so I don't have to fix this again?

**Comment by RafaelGreen1** [comment]
@bwobbones @acerix @acerix In my opinion this feature is really useful and also worth documentation here: https://fullcalendar.io/docs/event-clicking-hovering

**Comment by RafaelGreen1** [comment]
hi, any update on this? thanks

**Comment by bwobbones** [comment]
Not sure what to do here.  When I hear from any of the devs, I'll update my PR to the latest version.  

I wonder if there is no response because I'm not (yet) a paying customer?  I wonder if we could get any sponsorship in here from someone that @acerix or @arshaw will respond to?

**Comment by Xample** [comment]
@bwobbones I'm also in the need to get the clicked mouse information (or waiting for a dateContextmenu event). I'm using your [npm hack](https://www.npmjs.com/package/@bwobbones/fullcalendar5-rightclick) for now…

**Comment by bwobbones** [comment]
Thanks @Xample, no idea why they won't respond.  I'll keep the monkey patch up to date anyway as I'm using it myself.

**Comment by pamplona007** [comment]
Any news on this? My contractor is a paying client and we need this feature

**Comment by Xample** [comment]
@pamplona007 use the [monkey patch](https://www.npmjs.com/package/@bwobbones/fullcalendar5-rightclick) I'm using it in production.

**Comment by bwobbones** [comment]
Quick note to let anyone who is using it know that I've updated the monkey patch to work with FullCalendar v6.

npm i @bwobbones/fullcalendar5-rightclick

I'll fix my PR here also in the near future in the hope that @arshaw will look at it.

**Comment by bwobbones** [comment]
So...I closed this by mistake.  I honestly don't know what happened, I'll open a new one.

**Pull request closed without merging**
