### PR TITLE
feature  : support bootstrap 5

### PR DESCRIPTION
**Pull request by fabienwnklr**
After discussion  about [bootstrap 5 theme](https://github.com/fullcalendar/fullcalendar/issues/6299) i propose this dev for support bootstrap 5, no breaking changes. I only add 'bootstrap5' plugin : `themeSystem: 'bootstrap5'`.

_This including changements at bootstrap 5 [(please read this)](https://getbootstrap.com/docs/5.1/migration/)_

Please, don't hesitate to review this code (unknown environment like workspaces, jsx and more..) i hope this be good and will allow to go ahead.

Best regards.

### CODE REVIEW

**Comment by pjdevries** [comment]
I built and installed the PR on a site in my local dev environment. It's a Joomla! site, which I'm upgrading from version 3.x, using Bootstrap 2.x and FullCalendar `themeSystem:  'standard`', to 4.0, using Bootstrap 5 and FullCalendar `themeSystem:  'bootstrap5`' . At first glance I don't see anything out of the ordinary.

I did struggle a bit with a syntax error in `main.js` after the build, but I think it has nothing to do with the Bootstrap 5 implementation specifically. The error resulted from a comment in `.../packages/common/src/scrollgrid/SimpleScrollGrid.tsx` on line 178. This line reads: `liquidIsAbsolute // because its within a harness`. After removing the comment, the error disappeared and I had a usable `main.js`.

**Comment by fabienwnklr** [comment]
@pjdevries hi, for testing bootstra5 you have the manual testing into `packages/__tests__/bootstrap5
indeed this error has nothing to do width bootstrap 6 implementation sorry.. 

Thanks for you're feedback

**Review by AgentSmith0 — APPROVED** [review]

**Comment by nijikon** [comment]
@fabienwnklr from your perspective is this done?

**Comment by fabienwnklr** [comment]
@nijikon It's never done.. But it work :D so .. I think it's not so bad.

**Comment by arshaw** [comment]
@fabienwnklr , I took a different approach and [implemented it](https://github.com/fullcalendar/fullcalendar/tree/master/packages/bootstrap5/src), releasing it in v5.10.2. Please let me know if you see any issues with it. It required fewer modifications to the core code and less CSS. Thank you for inspiring me and for letting me learn from this PR.

**Comment by fabienwnklr** [comment]
@arshaw Hi, I’m glad I could help even a little.

**Pull request closed without merging**
