### PR TITLE
Should fix ssr problem "element is not defined" with nuxtjs and nextjs

### PR DESCRIPTION
**Pull request by Bornegrim**
Should fix ssr problem "element is not defined" with nuxtjs and nextjs

### CODE REVIEW

**Comment by arshaw** [comment]
this change will cause all browsers to always use the really slow fallback provided for the "matches" method.

On a more fundamental level, why doesn't nextjs/nuxtjs support `Element.prototype.matches` nor `Element.prototype.closest` ?

**Comment by haotangio** [comment]
I upgraded to nextjs 9.0.2 to be able to build. Just a temporary workaround.

**Comment by brendanmckenzie** [comment]
We are experiencing the same issue using ReactJS.NET.  

`Element` does not exist in the global namespace, just like `document` and `window`.

**Comment by zorrme** [comment]
Sam with angular universal, we should sanitize use of `document`, `window` and `Element`

**Comment by arshaw** [comment]
I'm questioning whether it's even a good idea to allow FullCalendar to render in an SSR environment: https://github.com/fullcalendar/fullcalendar/issues/4784#issuecomment-652559090

I'm closing this PR until we come to a consensus with that.

**Pull request closed without merging**
