### PR TITLE
Created year-view.html demo

### PR DESCRIPTION
**Pull request by markclowes**
Year view demo with extra css and dayRender logic

### CODE REVIEW

**Comment by acerix** [comment]
Thanks for the PR, is the demo as described here?

https://github.com/fullcalendar/fullcalendar/issues/1140

**Comment by markclowes** [comment]
It is kind of similar to #1140. It is a full year view in a single calendar window, not 12 mini calendars. Extra classes are added so each month can be styled differently.

**Comment by CalvinWu4** [comment]
Can you post a screenshot?

**Comment by arshaw** [comment]
this seems to be the demo for full-year view, but where is the actual implementation of full-year view?

**Comment by arshaw** [comment]
from this PR i assume? https://github.com/fullcalendar/fullcalendar/pull/3694

**Pull request closed without merging**
