### PR TITLE
added uzbek locale

### PR DESCRIPTION
**Pull request by Vohidjon**

### CODE REVIEW

**Comment by arshaw** [comment]
thanks. will try to get this into the next release.

**Comment by arshaw** [comment]
We have a momentjs translation file: https://github.com/moment/moment/blob/develop/locale/uz.js

But unfortunately we don't have jquery-ui uz.js file in here: https://github.com/jquery/jquery-ui/tree/master/ui/i18n

so I can't merge this right now unfortunately.

I eventually want to remove reliance upon jquery ui translations.

**Comment by arshaw** [comment]
i believe this can be ported over into the v4 codebase now

**Comment by Vohidjon** [comment]
Sorry I don't actively follow this repo. Do I need to do something to get this pull request merged? Happy to contribute :)

**Comment by arshaw** [comment]
this is released in v4.4.0:
https://github.com/fullcalendar/fullcalendar/releases/tag/v4.4.0

HOWEVER, the browser must support the `uz` locale in order for this to work. On my computer Firefox does, but Chrome doesn't for example. If you want more consistent support, it's advised to use the moment plugin.

**Pull request merged**
