### PR TITLE
added ability to use calendar on touch devices

### PR DESCRIPTION
**Pull request by marcucio**
Tested on latest Android and iOS and BlackBerry. I also added an experimental flag in utils.js (dragOnTouchDevices) that allows dragging events on touch divices.

### CODE REVIEW

**Comment by marcucio** [comment]
maybe you were using touch punch library, fast click might have fixed a few issues too. I found that some features worked without my changes (like event clicking) but other features like day click did not work properly.

**Comment by marcucio** [comment]
just another note, here is the related issue in the issue tracker:

https://code.google.com/p/fullcalendar/issues/detail?id=724

I also found a small issue on Windows Phone and Surface tablets that should be fixed today.

**Comment by marcucio** [comment]
this should be complete now, I pushed my windows phone and desktop changes

**Comment by tobia** [comment]
@marcucio I tried applying your patch on the current head (de08415) but I'm still not getting any touch support. If I try to move an event, resize it, or select an empty time range, my iPad simply scrolls the page. Do I need some other library or setting?

**Comment by samedii** [comment]
@tobia He did say it was experimental and did you set the flag?

**Comment by marcucio** [comment]
you will need to set dragOnTouchDevices = true and rebuild the project. Dragging is not well tested but basic functionality did seem to work on all the devices I tested on. The big issue is that if you have a list or scrollable calendar, how do you know if you want to scroll or if you want to drag, both actions will look the same to the OS. If the calendar is not in a scrollable window then the dragging events should work without an issue.

I'm thinking of adding a touch and hold gesture to initiate a drag but I haven't had time to try that out yet.

**Comment by kitarafrei** [comment]
Hi @marcucio I'm new on Github how can I download the entire package with your fix? I can't find it. Thanks

**Comment by marcucio** [comment]
the branch with my changes in it are here: https://github.com/marcucio/fullcalendar/tree/touch_device_fixes

I'm not sure if the dist build files are updated there, but my main fork should have updated dist files:

https://github.com/marcucio/fullcalendar

**Comment by kitarafrei** [comment]
Thanks @marcucio! I'll take a look and try to implement on my calendar!

**Comment by kitarafrei** [comment]
Hi @marcucio I donwloaded the files on the branch (first link) and I used the dist files but still had no luck to make it work on ipad. Is there anything else I need to do other than the usual call to start the calendar? Thanks!

**Comment by marcucio** [comment]
what exactly is not working?

**Comment by kitarafrei** [comment]
The drag and drop on the mobile, but I already figure it out! Thank you!!

**Comment by abstractcoder** [comment]
I use Bower and Bower Rails, and I managed to test your changes with the following entries

Bower Rails
    
    asset 'fullcalendar', '~>2.2.5', github: 'marcucio/fullcalendar', ref: '1f764c1a18937eae81d42490b9055d4a0fd55b3c'

Bower
    
    "fullcalendar": "git://github.com/marcucio/fullcalendar#1f764c1a18937eae81d42490b9055d4a0fd55b3c"

I also had to modify the fullcalendar.js file to set the flag to true

    var dragOnTouchDevices = true;

The dragging works, but the page also scrolls in a way that makes it unusable for me.

I'm using Touch Punch to enable dragging elsewhere in the application. Since dragging items onto the calendar requires jQuery UI that currently works on mobile devices, but users can't drag events that are already on the calendar on mobile devices since Touch Punch doesn't seem to affect FullCalendar.

I reverted to an old version (< 2.1) of FullCalendar that relied on jQuery UI but that didn't seem to work either.

Calling the jQuery UI draggable method on Calendar events works slightly better, but there are some graphical issues when reverting position and when dragging and dropping on day and week views.

**Comment by marcucio** [comment]
Yes this is why dragging with touch is not enabled by default, we haven’t found a good way to know if the user’s intentions are to scroll or drag, both actions look the same to us. Maybe we can add a drag button on the item where you can only drag the time if you use the handle to drag. Another idea was to do a longer hold to drag items.

If your calendar is full screen (doesn’t scroll) it shouldn’t be an issue, it is just an issue when your calendar is in a container that scrolls.

--
Mike Marcucio
marcucio.com <http://marcucio.com/>
mike@marcucio.com <mailto:mike@marcucio.com>

blog <http://blog.getitdoneapp.com/> | twitter <https://twitter.com/GetItDoneBlog> | facebook <https://www.facebook.com/GetItDoneTasks> | google+ <https://plus.google.com/u/0/b/116698933997097774721/+Marcucio/posts>

**Comment by MasterKale** [comment]
I have item dragging and creation working on Timeline events using a slightly-modified version of [jquery.ui.touch](https://github.com/joshgerdes/jquery.ui.touch). I apply it to calendar events thusly:

    eventAfterRender: function(event, element) {
        $(element).addTouch();
    }

Unfortunately this only enables you to click-and-drag to create an event if the start of the event is located **on a background event**...as in, so long as your finger goes down on a green square first, you can drag to anywhere else on the timeline as you'd expect. I still haven't nailed down the proper elements to apply `addTouch()` to so that you can create events from anywhere on the timeline. 

Clicking and dragging existing events works fine, though.

**Comment by dougestey** [comment]
Thank you for this @marcucio - you've helped me out a lot with an iPad project I'm working on in Ionic.

**Comment by KrunchMuffin** [comment]
was hoping I was going to be able to use this PR to add touch capabilities. I am trying to find a way to use the hover actions. Was hoping to do a single tap to replicate hover and 2nd tap to do click event on touch devices.
Tried adding this to `bindSegHandlers`, but doesn't get called.

        events.touchstart = function(seg, ev) {
            console.log(isTouchEvent(ev));
        };

**Comment by dtelaroli** [comment]
+1

**Comment by marcucio** [comment]
We convert touch events to mouse events so that this works properly. I was thinking of adding touch and hold to initiate a drag but I have not had time to try to implement it yet. I think touch and hold is a better ui experience than double tap because most systems do not use double tap regularly

**Comment by dtelaroli** [comment]
Thanks @MasterKale jquery.ui.touch resolved my issue.

**Comment by arshaw** [comment]
an official implementation of touch support has been released a few months ago: http://fullcalendar.io/docs/event_ui/Touch_Support/

@marcucio thank you for all the help you gave people in the meantime.

**Pull request closed without merging**
