### PR TITLE
Add missing keys to EventSourceFunc fetchInfo definition

### PR DESCRIPTION
**Pull request by hmnd**
In addition to title, extracts fetchInfo into exported interface and renames generic "arg" to "fetchInfo" to match the docs.

### CODE REVIEW

**Comment by acerix** [comment]
Please submit this ticket under Issues with a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/), then link this PR to it.

**Comment by hmnd** [comment]
@acerix I'm not quite sure what I would demonstrate? All this does is add a few missing keys to the event function TS definition...

**Comment by acerix** [comment]
Please open an issue describing the problem (eg. do you get an error when building?)  since we use issue for tracking and not PRs.

**Comment by arshaw** [comment]
this is no longer an issue in v5
https://fullcalendar.io/blog/2020/06/v5-official

**Pull request closed without merging**
