### PR TITLE
OptionsInput: Add missing property

### PR DESCRIPTION
**Pull request by tanoabeleyra**
Add `googleCalendarApiKey` property to `OptionsInput` interface

### CODE REVIEW

**Comment by acerix** [comment]
Thanks for the PR. Part of this issue https://github.com/fullcalendar/fullcalendar/issues/4690

**Comment by tanoabeleyra** [comment]
Hi @acerix, I don't know about the other missing properties, should I add them for this to be merged?

**Comment by tanoabeleyra** [comment]
Any update on this @acerix @arshaw ?

**Comment by arshaw** [comment]
i just made this fix, but i did it in the google-calendar plugin, not core. it's in master. I'll release pretty soon

**Comment by tanoabeleyra** [comment]
Great, thanks!

**Comment by arshaw** [comment]
This was fixed in 4.3.0 though please start using 4.3.1
Releases: https://github.com/fullcalendar/fullcalendar/releases

**Pull request closed without merging**
