### PR TITLE
Arbitrary differing slotMinutes increments

### PR DESCRIPTION
**Pull request by avanti-technologies**
https://github.com/fullcalendar/fullcalendar/issues/472

and 

https://github.com/fullcalendar/fullcalendar/issues/3287

### CODE REVIEW

**Comment by arshaw** [comment]
is this an implementation for the Agenda views?

it looks like your commit history got really messed. did you accidentally rebase?

**Comment by avanti-technologies** [comment]
Hello,

This implementation should work fine with fullcalendar stand alone. Agenda views are supported with this one.
This implementation is separated from the scheduler implementation i've done.

In the demo folder, you can find the "custom-range.html" file to see how it looks like.
Feel free to ask any question!

And yea, the History got messed at some point. I can't really tell you what happend but it looks like the intern had fun with git haha

**Comment by kleisauke** [comment]
Just tested this. Dragging and dropping seems not to be working (it snaps on the wrong hours). 
And I don't like to fill out the `customTimeSlot` array with duration's, I think this is better:
```javascript
slots: [
  {start: '07:35', end: '08:20'},
  {start: '08:25', end: '09:10'},
],
```
(just my opinion)

I could take a look to my old PR #238 and see if I can rebase (and squash the commits) against [v3.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.1). (I'm not sure how much demand there is for this feature).
For anyone interested, the demo of my old PR can you test [here](http://kleisauke.nl/fullcalendar/demos/timeslots-views.html).

**Comment by arshaw** [comment]
closing until a rebase happens and @kleisauke concerns are addressed

**Comment by kleisauke** [comment]
@arshaw If you want, I can rebase my old pull request (with master), make some automated tests and issue a new pull request.

**Comment by arshaw** [comment]
hi @kleisauke . rebasing at the very least would be great

**Comment by kleisauke** [comment]
@arshaw Rebased and cleaned! See: kleisauke@ea528e0

You can test it here:
http://kleisauke.nl/fullcalendar3-5-0/demos/timeslots-views.html
and here:
http://kleisauke.nl/fullcalendar3-5-0/demos/timeslots-views-without-snap.html

**Comment by kleisauke** [comment]
@arshaw Did you intended to reopen this pull request? I'm not sure if this is being updated.

Anyways, I've rebased my fork again. See: https://github.com/kleisauke/fullcalendar/commit/7759843ae7dca5f4bc50633ee514dbb6f0554617. My (closed) pull request can be found at https://github.com/fullcalendar/fullcalendar/pull/238.

**Comment by arshaw** [comment]
@kleisauke I was getting mixed up about who the owner of this PR was. I'll re-close this. I thought you had submitted a newer PR, but seems like you are simply maintaining your fork. Looks like you are keeping the folks on #472 updated. thanks.

**Comment by kleisauke** [comment]
@arshaw I maintain my fork to always get the newest features/bug-fixes (it's in production use on a couple of websites, usually schools that have varied timeslots). It would be awesome if this integrated in fullcalendar, although I'm not sure if this will ever happen (it's a uncommon feature). Let me know if I should make a new pull request.

**Comment by rajkrishna1590** [comment]
Hi @kleisauke, 
capture
i want to render one more slatRowHtml.. i  dont know how to do.. pls refer this attachement

**Pull request closed without merging**
