### PR TITLE
Implemented iCalendar/ICS Event Source

### PR DESCRIPTION
**Pull request by haukepribnow**
This pull request includes an implementation of an Event Source that supports the iCalendar/ICS standard. It is currently based on [a fork of `ical-expander`](https://github.com/haukepribnow/ical-expander) that I created to make `ical-expander` a Universal JavaScript Module. My fork and [the original `ical-expander`](https://github.com/mifi/ical-expander) are based on [`ical.js`](https://github.com/mozilla-comm/ical.js).

[I hope that my forked branch will be pulled into the original `ical-expander` project at some point.](https://github.com/mifi/ical-expander/pull/2) Once this happens, I would also change the `ical-expander` dependency from the GitHub source into the "normal" package source.

### CODE REVIEW

**Comment by arshaw** [comment]
hi @haukepribnow this is pretty cool. Both `EventSource` and `EventSourceParser` are exposed

https://github.com/fullcalendar/fullcalendar/blob/v3.5/src/models/event-source/EventSource.js#L155
https://github.com/fullcalendar/fullcalendar/blob/v3.5/src/models/event-source/EventSourceParser.js#L29

and you can get ahold of them like this:

```js
var EventSource = $.fullCalendar.EventSource;
```

so you could easily write this as a plugin for FullCalendar and not have it be part of the core repo, which would be preferable, at least at the start.

Does that make sense?

**Comment by haukepribnow** [comment]
Thank you for your feedback. Turning iCalendar integration in fullcalendar into a plugin for fullcalendar makes sense to me.

On a different note: The author of `ical-expander` stated in the meantime that [he does not want to turn his project into a Universal JavaScript Module](https://github.com/mifi/ical-expander/pull/2#issuecomment-325956515). Instead, he suggests to use Browserify or webpack.

Now I wonder what the best solution would be for a fullcalender iCalendar plugin as suggested by you. Would you recommend to use Browserify or webpack for the plugin? Are you maybe considering to move your own fullcalendar project towards one of the two?

After all, I wonder a bit if it makes sense to introduce Browserify or webpack in my fullcalendar plugin, while fullcalendar remains a Universal JavaScript Module without using any of the two. Does that really make sense? 

To be honest, this confusion might come from the fact that I have been more of a "user" of modules such as yours so far. So I'm not really into the ecosystem of and npm modules and packages yet. (Coming more from a C# background.) So any hints on how to proceed now would be greatly appreciated. :-)

**Comment by arshaw** [comment]
@haukepribnow, fullcalendar is implemented as a UMD module:
https://github.com/fullcalendar/fullcalendar/blob/v3.5.0/dist/fullcalendar.js#L7-L17

UMD modules are meant to work with Browserify and Webpack.

But since your main dependency (ical-expander) is not written as a UMD, I suggest implementing your plugin as an ES6 modules (which works with Browserify and Webpack). It can consume fullcalendar all the same.

The exact steps are rather complicated :(
https://www.smashingmagazine.com/2016/02/writing-reusable-components-es6/

**Comment by arshaw** [comment]
I'm closing this PR in favor of https://github.com/fullcalendar/fullcalendar/pull/5969, which has been released in v5.5.0. Please see my comment here: https://github.com/fullcalendar/fullcalendar/issues/1580#issuecomment-748535186

**Pull request closed without merging**
