### PR TITLE
Add segment argument to hook eventRender that allow user to customize event rendering based on information about current rendered segment

### PR DESCRIPTION
**Pull request by w-site**
Add segment argument to hook eventRender that allow user to customize event rendering based on information about current rendered segment.

It will be very helpful to get additional information about segment. For ex. attributes firstRowDayIndex, lastRowDayIndex for customization my event.
For ex. in month view if I know firstRowDayIndex, lastRowDayIndex I can figure out what is the size of current rendered segment of event and based on this information I can attach html that I need, this is one of the case.

I think in any case info about segment will be helpfull for some case.
Thanks.

### CODE REVIEW

**Comment by w-site** [comment]
About error from travis 
Worker information
hostname: 312a1f82-c019-40b5-b526-4effd3e6d179@1.i-04a0047-production-2-worker-org-ec2.travisci.net
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: 9019820 travisci/ci-garnet:packer-1503972846 (via amqp)
startup: 853.785803ms
oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

**Comment by acerix** [comment]
Please submit a ticket under Issues with the feature you are requesting, then link this PR to it.

It looks like you want a way to access the current `segment` from within `eventRender()` , which would also resolve this issue:

https://github.com/fullcalendar/fullcalendar/issues/3311

**Comment by w-site** [comment]
@acerix Thanks for answer.
Yes you are absolutely correct about "It looks like you want a way to access the current segment from within eventRender()", and seems that it resolve https://github.com/fullcalendar/fullcalendar/issues/3311 because segment have options isStart and is End

I created issue as you say above: https://github.com/fullcalendar/fullcalendar/issues/3956

**Comment by w-site** [comment]
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
See the blog post »

https://fullcalendar.io/docs/v4/eventRender

isStart, isEnd, isMirror at least

**Pull request closed without merging**
