### PR TITLE
Deprecate event shorthand methods

### PR DESCRIPTION
**Pull request by effyteva**
Following jQuery issue #3214
Important for those using jQuery migrate 3.0.1.

### CODE REVIEW

**Comment by arshaw** [comment]
could you point me to some documentation somewhere to prove that jQuery is deprecating these methods?

**Comment by effyteva** [comment]
Sure, it's https://github.com/jquery/jquery/issues/3214

**Comment by arshaw** [comment]
thanks

**Comment by neroux** [comment]
Nothing has been deprecated yet. There are proposals, ideas, and discussions and currently it seems they might actually go through with it but thats all for the moment. No action has been taken so far.

**Comment by arshaw** [comment]
gonna close this because jquery has been removed from v4 anyway

**Pull request closed without merging**
