### PR TITLE
Function to remove event sources

### PR DESCRIPTION
**Pull request by bmelo**
I had to add this feature to a project. I followed #948

### CODE REVIEW

**Comment by arshaw** [comment]
thanks for this! code looks good.

would you mind adding some tests?
https://github.com/fullcalendar/fullcalendar/wiki/Automated-Tests
https://github.com/fullcalendar/fullcalendar/tree/master/tests/automated

**Comment by avinashramireddy-rapidd** [comment]
Hi,
I have  included lines required for remove event sources by following your feature.

Basically,I want to render new view and pass different data.But it is rendering month view data also.
So I tried this feature to remove all sources.

Then in my custom view I added 
```

renderEvents: function () {
         
        $('#calendar').fullCalendar('removeEvents').fullCalendar('removeEventSources')...
     
```
but I am getting error as follows:

**jquery-1.10.2.js:634 Uncaught RangeError: Maximum call stack size exceeded** .

What could be possible solution.i tried.But found nothing. Please help me

**Comment by bmelo** [comment]
@arshaw I'll read about this and try to implement. Thanks.

**Comment by bmelo** [comment]
@avinashramireddy-rapidd, when are you calling renderEvents? 
Did you debug the code to find the point that is causing the loop?

**Comment by avinashramireddy-rapidd** [comment]
Yes,I did.It is just happening in first place.

```
var FC = $.fullCalendar, // a reference to FullCalendar's root namespace
    View = FC.View, // the class that all views must inherit from
    ListView; // our subclass

ListView = View.extend({ // make a subclass of View  
 initialize: function () {
        //console.log("initialize");
    },
    render: function () {
        this.el.html('<table class="fc-list-event-table" />');
    },
    setHeight: function (height, isAuto) { 
    },
   renderEvents: function (e) {
        console.log("custom agenda render events");
        $('#calendar').fullCalendar('removeEventSources');
        //Calling signarR to get list of events
.......


FC.views.customAgenda = ListView;
```


In my cshtml page, I have

  $('#calendar').fullCalendar({
                header:
                {
                    left: 'prev,next',
                    center: 'month,agendaWeek,agendaDay,customAgenda',
                    right: 'null'
                },
                defaultView: 'month',
                events: function (start, end, timezone, callback) {
                   console.log("here comes events for month,week,day");
                   // Calling signarR  to get list of month or week or day events
                }

In this scenario when I switch from defaultview:month to customAgenda it is triggering
"custom agenda render events"  infinity times. 
There are other problems also which I can't even figure out why happening in first place.
I want to clear out one by one starting with this one.
Can you help me?

**Comment by arshaw** [comment]
[Code complete](https://github.com/fullcalendar/fullcalendar/commits/v2.8.0-dev) and [docs written](https://github.com/fullcalendar/fullcalendar/commits/docs-2.0) but not yet released. Will update this thread when released.

I wrote tests for this.

This method is called `removeEventSources`

**Comment by arshaw** [comment]
Released in [v2.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.8.0).

http://fullcalendar.io/docs/event_data/removeEventSources/

**Comment by avinashramireddy-rapidd** [comment]
@arshaw 
Hi,
First of all,thanks for the update.

I am working on **custom view which has custom button(daterangepicker)** shown. When I change date range,I want to **call function which is written via using signalR.** This signalR is new concept to me which was already implemented by one of my colleagues.(tried taking help,but he doesn't know about extending views which was done by me only)

Now I am **unable to understand whether this **signalR functions are called when date range is changed or not.**Because in custom agenda view,**renderEvents is called more than once with different data.**

I am quite sure something has to  do with the **signalR**(Reason behind using signalR is that,I don't want to refresh page or calendar when events are updated or removed or added.The signalR will do just fine in this situation.)

Please help me.**Seriously stuck from one week**.I feel that I have complicated problem. Didn't get any decent solution with this scenario.

**Pull request closed without merging**
