### PR TITLE
Add aria-label to toolbar icon buttons

### PR DESCRIPTION
**Pull request by blissdev**
Very initial work on addressing issues brought forward in #2536. Began by trying to address ARIA labeling of previous/next buttons which only use icons.

**Open Questions**
1. Any advice on the approach or specific implementation details would be appreciated.
2. Are tests desired to check for the attribute? How to test a11y?
2. It doesn't seem there is currently appropriate text for these buttons, which for English would be "Previous" and "Next" and would be needed in all other locales as well, so what is the appropriate way to acquire this text? Can we start with a few common locales?
3. What else is needed to make this addition viable?

Any feedback would be appreciated, thanks!

### CODE REVIEW

**Comment by blissdev** [comment]
There's a test failure:

```
Expected ({ 0: HTMLNode, length: 1, prevObject: ({ 0: HTMLNode, length: 1 }) }) to have text 'تموز يوليو ٢٠١٦'.
/home/travis/build/fullcalendar/fullcalendar/tmp/compiled-tests.js:13777:39
```

This seems unrelated to my changes, but please let me know if I'm missing something.

**Comment by acerix** [comment]
Thanks for the PR

**Comment by arshaw** [comment]
released. thanks

**Comment by blissdev** [comment]
@arshaw @acerix Hi, I'm a bit confused. This is only the beginning of the work. Currently as implemented this only uses the `buttonName` as the `aria-label`. From what I can tell in English this will be "prev" and "next", where it should really be "previous". Also in some locales this is represented as a symbol which does not provide accessible text from what I can tell. I was hoping to get feedback on how to proceed foward, I don't think it is ready to land yet.

**Comment by acerix** [comment]
Using the button text is better than nothing, and a good start on https://github.com/fullcalendar/fullcalendar/issues/2536.

Other buttons are translated with the [buttonText](https://github.com/fullcalendar/fullcalendar/blob/master/src/options.ts#L51) object, so I suggest making a copy of that eg. `buttonAriaLabels` and using it in the same way to add the proper text.  I agree it should be "previous" instead of "prev" and change based on the selected locale, but not sure that "prev" could just be replaced by "previous" in `buttonText`.

Tests are always nice, but this change is pretty straightforward and can easily be seen in the demos (looking at DOM).  Maybe something like [gulp-accessibility](https://www.npmjs.com/package/gulp-accessibility) could test for a11y in general.

**Pull request merged**
