### PR TITLE
Add nepali locale

### PR DESCRIPTION
**Pull request by lalustine7**

### CODE REVIEW

**Comment by arshaw** [comment]
thanks @lalustine7

**Comment by lalspicesresearch** [comment]
@arshaw now, is there anything i need to do?

**Comment by lalustine7** [comment]
@arshaw now, is there anything i need to do?

**Comment by arshaw** [comment]
there's nothing else for you to do. i plan to release this in the next version. thanks!

**Comment by lalustine7** [comment]
ok then can i close the pull request ?

**Comment by acerix** [comment]
Please leave it open, it will be closed when merged.

**Comment by arshaw** [comment]
apparently the locale code for Nepali is `ne`, not `np`, so I changed it

**Comment by arshaw** [comment]
though the buttons translate for me, the dates do not. the date translations are the responsibility of the browser. @lalustine7 , after I release this code, I'll ask you to see if the date translations appear for you...

**Comment by lalspicesresearch** [comment]
ok, i will check it when it is released. Is there anyway to solve it if it does not appear @arshaw ?

**Comment by arshaw** [comment]
This is released.

@lalspicesresearch , can you go to https://fullcalendar.io/docs/locale-demo , choose `ne`, and see if everything translates?

If it doesn't work, there's no way to fix it.

You could try a different technique of using the [moment connector](https://fullcalendar.io/docs/moment-plugin) to handle the translation. You'll need to make sure you include moment's Nepali translation file

**Comment by lalspicesresearch** [comment]
Dates are not translated, no issue but is there any way to translate day name like sunday, monday in nepali ? I can work on file like before if needed to translate it. @arshaw

**Comment by lalustine7** [comment]
Date not translated, no problem. But is there anyway to translate day of week like sunday, monday in nepali? I can work on the files if needed like before @arshaw

**Comment by arshaw** [comment]
The translations for month and weekday are not within FullCalendar's translation files. The web browser is responsible for this. So, it's a really difficult problem.

I suggested using Moment, but there is a problem with that too: https://github.com/fullcalendar/fullcalendar/issues/5683

Please see the second codepen link in that ticket for a workaround.

**Comment by lalustine7** [comment]
So, nepali locale is not compatible for fullcalendar @arshaw ?

**Comment by arshaw** [comment]
@lalustine7 , nepali is not fully compatible right now. however, then this issue is completed, it will be fixed:
https://github.com/fullcalendar/fullcalendar/issues/5683
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by lalspicesresearch** [comment]
@arshaw i have subscribed and liked as you aske me

**Pull request merged**
