### PR TITLE
Enable  `event.allDay` resizable.

### PR DESCRIPTION
**Pull request by hetz**
Enable allDay can resize in month view.

### CODE REVIEW

**Comment by espen** [comment]
allDay can already resize in a month view, no? Try resizing a event in the month view at http://fullcalendar.io/js/fullcalendar-2.4.0/demos/basic-views.html

Regardless, you have made a pull request editing the generated dist file. For a pull request to be accepted you need to edit the src file.

**Comment by hetz** [comment]
@espen ,thx you answer :smile: .
If event has allDay, resize enable in month, but I think event has part time resizeable too.
I try change this code,more flexible logic.

**Comment by hetz** [comment]
Hi @espen , I think when allDay event in month view, people can resizable, they resizable allDay event get long by interval day(24h).

**Comment by arshaw** [comment]
duplicate of #2441

**Pull request closed without merging**
