### PR TITLE
add columnHead option to show/hide column heading (#3438)

### PR DESCRIPTION
**Pull request by caseyjhol**
Solves #3438.

See a demo here: https://plnkr.co/edit/W8nw1DKVenJV72QMrhn8?p=preview

### CODE REVIEW

**Comment by arshaw** [comment]
looks great! could you add a quick test for this?

**Comment by caseyjhol** [comment]
Hoping to get a test done soon.

**Comment by caseyjhol** [comment]
@arshaw Which folder am I supposed to put this test in? Seems like the automated tests Wiki might be a bit outdated.

**Comment by caseyjhol** [comment]
@arshaw Added tests.

**Comment by arshaw** [comment]
thanks @caseyjhol

**Comment by arshaw** [comment]
queued for release. i decided to change name to `columnHeading`

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)

docs: https://fullcalendar.io/docs/display/columnHeader/

(renamed to *columnHeader*)

**Pull request merged**
