### PR TITLE
Year View with 12 Mini-Calendars #1140

### PR DESCRIPTION
**Pull request by dusanm65**

### CODE REVIEW

**Comment by xvisionicaro** [comment]
Hey man, this is realy nice.

I noticed that the events on the year view appears one day before than on the other views. Do you know what can be causing this problem?

**Comment by dusanm65** [comment]
Thanks mate, no idea, I can't reproduce it either, could you please describe how I could make it happen.
I create events by dragging mouse, or from an application. And I see them correctly on month, week, list.

**Comment by xvisionicaro** [comment]
That's really weird, man. 
If I open one of the basic demos and add a year view I got this behaviour.

**Comment by dusanm65** [comment]
Super weird, I did that with demos/basic-views.html and selectable.html just added year and all the events appear with correct start date, I've got no idea why it wouldn't work in your case

**Comment by xvisionicaro** [comment]
Could the timezone affect that? I'm on GMT-3.

**Comment by dusanm65** [comment]
Yep, that is it, I will get it fixed

**Comment by dusanm65** [comment]
can you try if it's fixed for you?

**Comment by xvisionicaro** [comment]
Yep, this fixed it for me. Thanks a lot, mate.

**Comment by laoneo** [comment]
Will this one get a chance to get into the core?

**Comment by Invincibear** [comment]
I'm trying to port this to FCv4 and am having issues converting method buildDayGrids() which is responsible for generating new dayGrids. Any pointers for generating generic dayGrids in FCv4?

**Comment by Invincibear** [comment]
I'm trying to port this to FCv4 and am having issues converting method buildDayGrids() in @dusanm65's code which is responsible for generating new dayGrids. 

@arshaw Any pointers for generating generic dayGrids in FCv4? Hooking into existing dayGrid generators is preferred, alternatively, instantiating a new FC instance for each dayGrid might also work but would incur heavy resource usage & reduced performance penalties.

**Comment by simon-franz** [comment]
Is there any chance that this will be integrated into core? would definitly be a nice addition!

**Comment by henrikfischer** [comment]
If this is still relevant I made this in React :

`const months = ['01','02','03','04','05','06','07','08','09','10','11','12']

{months.map((item, i) => (
  <FullCalendar
    key={'month' + item}
    defaultView="dayGridMonth"
    defaultDate={`2020-${months[i]}-01`}
    plugins={[dayGridPlugin, timeGridPlugin]}
    height="auto"
    weekNumbers={false}
    firstDay={1}
    header={{ left: '', center: 'title', right: '' }}
    views={{
      dayGridMonth: {
        titleFormat: {
          month: 'long'
        }
      }
    }}
    showNonCurrentDates={false}
    fixedWeekCount={false}
  />
))}`

Can add a codepen later.

**Comment by cesarmtz93-wit** [comment]
any update on this?

**Comment by danir-de** [comment]
What's the current status on this?

**Comment by arshaw** [comment]
I've made a separate implementation of this and released it: https://fullcalendar.io/blog/2023/01/multimonth-and-more

@dusanm65, thank you for this fork and for helping so many people with this feature.

**Pull request closed without merging**
