### PR TITLE
Add support to ctrl+click multi dates on Windows

### PR DESCRIPTION
**Pull request by SudharakaP**
This checks whether the platform is windows and if so adds support to ctrl click and select multiple days on the calendar.

### CODE REVIEW

**Comment by acerix** [comment]
Thanks for the PR but please submit an issue explaining the problem that this is fixing and link it to this PR.

**Comment by SudharakaP** [comment]
@acerix : Sorry for the mistake, and thanks for letting me know. I have submitted and issue and linked it.

**Comment by arshaw** [comment]
similar solution as mentioned in https://github.com/fullcalendar/fullcalendar/issues/3823#issuecomment-327797093

**Comment by arshaw** [comment]
thanks. will get this fix (or a fix like it) in the next release

**Comment by stadja** [comment]
I would really LOVE to see that merged very soon, I just stumbled in this problem today and if this is a fix, that would be awesome to have :)
<3

**Comment by artem-karnaukh** [comment]
hey @arshaw , is there any news on this? It would be extremely helpfull feature to have and the fix seems to be easy enough. Thanks for your help, your product is awesome! Cheers.

**Comment by arshaw** [comment]
When I first saw this report, I must have misinterpreted it. I thought it was cross-browser fix to make behavior more consistent between windows and mac. after looking at it further, I see that it's actually an attempt at adding a *feature* specifically for Windows. I'm not crazy about adding Windows-only features. Is there a Mac equivalent? I believe in Mac you can Command+click in Mac to get the same effect. If we were to add this feature, I'd also like to add it for Mac.

However, even if we were to adjust the `isPrimaryMouseButton` function to accommodate both WIndows and Mac, there's still a lot more work to do to get "selecting and dragging multiple events" to work (which is what the https://github.com/fullcalendar/fullcalendar/issues/4387 ticket is all about). There are many more complexities with mutating the event data and showing a "selected" state of event.

Since this PR is far from what's needed to achieve this, I'm going to close it. But we can use #4387 as a ticket to track demand, and if demand increases, we'll consider adding this from scratch.

**Comment by arshaw** [comment]
it would be a lot more work to get selecting multiple *dates* working too

**Comment by dhruvaraj-jaiswal** [comment]
> When I first saw this report, I must have misinterpreted it. I thought it was cross-browser fix to make behavior more consistent between windows and mac. after looking at it further, I see that it's actually an attempt at adding a _feature_ specifically for Windows. I'm not crazy about adding Windows-only features. Is there a Mac equivalent? I believe in Mac you can Command+click in Mac to get the same effect. If we were to add this feature, I'd also like to add it for Mac.
> 
> However, even if we were to adjust the `isPrimaryMouseButton` function to accommodate both WIndows and Mac, there's still a lot more work to do to get "selecting and dragging multiple events" to work (which is what the #4387 ticket is all about). There are many more complexities with mutating the event data and showing a "selected" state of event.
> 
> Since this PR is far from what's needed to achieve this, I'm going to close it. But we can use #4387 as a ticket to track demand, and if demand increases, we'll consider adding this from scratch.

I need this feature in my calendar.

**Pull request closed without merging**
