### PR TITLE
rendering hooks for columnHeader (columnHeaderHtml, columnHeaderText)

### LINKED ISSUE #3078: expose rendering hooks for day headers
[requested by](https://github.com/fullcalendar/fullcalendar-scheduler/issues/142) @iamkoby and @mattdanna:

> Currently the only ability is to edit `slotLabelFormat`. 
> Let's say the format is "dd DD", I would love the option to edit css of that column but I can't separate classes of the "dd" and the "DD". The desired result is:
> screenshot 2016-02-24 12 03 02
> 
> I am now patching this with editing the html in the viewRender function:
> 
> ```
> viewRender: function(view, element){
>     element.find('.fc-head .fc-time-area th.fc-widget-header .fc-cell-text').each(function(i, col){
>         var content = $(col).text().trim().split(',');
>         $(col).html('<span class="day-name">' + content[0] + '</span><span class="day-num">' + content[1] + '</span>');
>     });
> },
> ```

### PR DESCRIPTION
**Pull request by caseyjhol**
Fixes #3078.

Also deprecates columnFormat in favor of columnHeadFormat. Wasn't sure if you wanted to change the names to column**Header** * or not, but I kept them as columnHead as you originally suggested. I can rename them if you want.

See a preview: https://plnkr.co/edit/0OYN5ipVdCpSt2R3SFTT?p=preview

Working on tests.

### CODE REVIEW

**Comment by caseyjhol** [comment]
@arshaw Do you want me to create a separate test file for columnHeadHtml and columnHeadText, or lump it in with columnHeadFormat?

**Comment by arshaw** [comment]
looks good! could you rename it to `columnHeader*` ?

**Comment by arshaw** [comment]
the renames and adjustment to typescript look good!

can you write tests for the new functionality?

**Comment by caseyjhol** [comment]
On my to-do list. Hoping to have those done this week.

**Comment by arshaw** [comment]
looks good, thank you! will try to get this into the next minor release

**Pull request merged**
