### PR TITLE
Implemented multiple definitions for businessHours (language fixed)

### PR DESCRIPTION
**Pull request by dtmonterrey**
This new pull request has the language fixed (in the previous one #232 I mess it up).

### CODE REVIEW

**Comment by billmn** [comment]
What about merge this commit?
Multiple businessHours is a very nice feature!

**Comment by espen** [comment]
The way I am handling this, because business hours in my app change every week, is by having an event source for business hours and adding background events.

**Comment by caiotarifa** [comment]
:+1:

**Comment by arshaw** [comment]
though i am closing this PR for organizational reasons, I will reference it and leverage it when tackling #2686

**Pull request closed without merging**
