### PR TITLE
Check if dayRange index exists

### PR DESCRIPTION
**Pull request by BenevidesLecontes**
Using listWeek view is throwing error `Cannot read property 'startMs' of undefined` when `dayRanges[dayIndex + 1]` doesn't exists.

### CODE REVIEW

**Comment by arshaw** [comment]
@BenevidesLecontes would you mind creating a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) in order to prove that there's a bug first?

**Comment by arshaw** [comment]
nevermind, seems to be a fix for this issue: https://github.com/fullcalendar/fullcalendar/issues/3843

**Comment by BenevidesLecontes** [comment]
@arshaw sorry for the delay, i was using the calendar with angular (4), it was working in all views except on listWeek view because of this. I didn't posted the plunker or other demonstration of this bug, because i was busy doing the calendar for my company.

**Comment by arshaw** [comment]
no problem.

i'm going to close this pull request because v3.6.0 released a fix for the underlying problem

**Pull request closed without merging**
