### PR TITLE
Adds current time indicator when possible

### PR DESCRIPTION
**Pull request by nullquery**
Implementation of issue 143: Current time indicator in agenda views

I'm not sure if this implementation follows the guidelines, and it may well be that it could be improved upon by someone who is more familiar with the inner workings of the code. It also lacks a configurable option to disable this functionality, but it's a good start to implement this functionality IMO.

I've tested it in the week and day views and it works there. In the month view the indicator is absent (which is logical since it doesn't have any indicators for time).

### CODE REVIEW

**Comment by nullquery** [comment]
Uh. My PR wasn't merged and now we had to manually resolve the conflicts to remain up-to-date.

Is this going to be merged? x.x

**Comment by nullquery** [comment]
If you copy/paste my changes manually the conflicts will be resolved.

**Comment by momoteRyanmt** [comment]
please merge, this feature request has been around of literally years!!!

**Comment by ambicoder** [comment]
I have copied the code found here so that I can implement the timeindicator feature.
I cannot make it to work though....I have found some issues with the code.For instance in renderTimeIndicator() ....there is a reference to this.el.find(".fc-today").length
el though is not listed as a method/property inside the TimeGrid object

**Comment by samedii** [comment]
Is the code crashing? Otherwise you should know there's like a million inheritances in the code

**Comment by ambicoder** [comment]
In the console I get "Cannot read property 'find' of null",,,and in week/day view the calendar is not even displayed....yes I understand that there many inheritances and searching though all this code is not easy....so I hope the feature gets merged soon

**Comment by samedii** [comment]
Huge changes have been made of late which broke most of my code too. I think this was in an effort to clean stuff up and allow for mods to be added on top of fullcalendar (instead of having to recompile everything)

**Comment by ambicoder** [comment]
What do you suggest I do?

**Comment by chamerling** [comment]
Hi all, 
Any update on this PR?
Thanks!

**Comment by espen** [comment]
Has this been discussed in the issue tracker? Please see https://github.com/arshaw/fullcalendar/wiki/Contributing-Features

**Comment by arshaw** [comment]
closing this issue until #414 is addressed, in which case I'll refer back to this PR.

**Pull request closed without merging**
