### PR TITLE
Added Galician language

### PR DESCRIPTION
**Pull request by iago1460**
Thanks a lot for the great library. Here is Galician translation.

### CODE REVIEW

**Comment by arshaw** [comment]
thank you for this! would you be able to submit a new PR with only your changes to `lang/gl.js`? please do not include the changes to anything in the `dist/` directory. really appreciate it.

**Comment by iago1460** [comment]
@arshaw Done

Regards

**Comment by arshaw** [comment]
thanks.

note to self: cherry-pick 649a2c9a9da570c3794a31512c0f83343178b93b

**Comment by arshaw** [comment]
[Code complete](https://github.com/fullcalendar/fullcalendar/commits/v2.8.0-dev) and slated for v2.8.0 ([wip docs](https://github.com/fullcalendar/fullcalendar/commits/docs-2.0)). Will notify when released.

**Comment by arshaw** [comment]
Released in [v2.8.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.8.0).

**Pull request closed without merging**
