### PR TITLE
fix jsEvent not working properly with the unselect callback when selecting another time slot on the calendar view

### PR DESCRIPTION
**Pull request by caseyjhol**
Recreate: http://jsbin.com/bumutohezu/edit?html,js,output

Select a time slot on the calendar. Then, select another. jsEvent is `undefined`.

Fix: https://plnkr.co/edit/rc6LWxR5HS4dCVGGwisz?p=preview

### CODE REVIEW

**Comment by arshaw** [comment]
thanks for this fix for #3341

**Comment by arshaw** [comment]
i might have closed this by accident

**Comment by arshaw** [comment]
durp, it was closed because the base branch was deleted. ill find a way to get it in there

**Comment by caseyjhol** [comment]
I can resubmit the pull request on master if that's easier for you.

**Comment by arshaw** [comment]
it's ok. queued for release: b0732586c6e29bfe63d096968b770eadb1cae84d

**Comment by arshaw** [comment]
released in 3.6.0

**Pull request closed without merging**
