### PR TITLE
slotLabelFormat, display a range (PR)

### PR DESCRIPTION
**Pull request by leehan0617**
make new option initalize fullcalendar 'viewSubSlotLabel' , default : false 
if 
```
viewSubSlotLabel : true
```
and fullcalendar rendering

<table>
<tr><td>00:00 ~ 00:30</td><td></td><td></td></tr>
<tr><td>00:30 ~ 01:00</td><td></td><td></td></tr>
<tr><td>01:00 ~ 01:30</td><td></td><td></td></tr>
<tr><td>01:30 ~ 02:00</td><td></td><td></td></tr>
</table>

After My aim is update this code to useing calmly
I wish my code will help other developer.
Thanks.

### CODE REVIEW

**Comment by arshaw** [comment]
Note to self and others, this PR addresses this issue:
https://github.com/fullcalendar/fullcalendar/issues/2887

**Comment by arshaw** [comment]
My initial reactions:

Could we leverage [titleRangeSeparator](https://github.com/fullcalendar/fullcalendar/issues/3200) instead of hardcoding a `~` ?

Also, I'm not crazy about the name. I'd rather call it something like `slotLabelIntervalIsRange`, though that might be too verbose.

**Comment by leehan0617** [comment]
ok I rewrite code about this issue . thanks

**Comment by reilg** [comment]
Was this feature ever implemented?

**Comment by acerix** [comment]
No, there is still an open ticket for this feature:
https://github.com/fullcalendar/fullcalendar/issues/2887
↑
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Pull request closed without merging**
