### PR TITLE
Allow the event to define if the end time should be shown

### PR DESCRIPTION
**Pull request by laoneo**
Support a new property for an event to define if the event end time should be shown or not.

### CODE REVIEW

**Comment by acerix** [comment]
Thanks for the PR.  Please create a new issue for this feature and link the PR to it

**Comment by laoneo** [comment]
Issue submitted #4034.

**Comment by acerix** [comment]
Thanks

**Comment by laoneo** [comment]
Any interest to get this one merged? Then I will fix the conflicts, otherwise feel free to close.

**Comment by arshaw** [comment]
I can migrate the code to the latest v5, but this feature still needs tests. @laoneo , can you write automated tests for the this PR's project tree?

**Comment by laoneo** [comment]
I can try, hope you have a docker container available. Or how to get started?

**Pull request closed without merging**
