### PR TITLE
fullcalendar-Jalaali 3.0.1

### PR DESCRIPTION
**Pull request by Natico**
change and update many files for support fullcalendar -jalaali 3.0.1

### CODE REVIEW

**Comment by espen** [comment]
Salam @Natico. Thanks for making a pull request - kheily khoob. But there are a lot of changes here that are not relevant for a pull request and files that shouldn't be changed.

**Comment by laoneo** [comment]
You should rebase your branch, otherwise it will be unlikely to get merged.

**Comment by arshaw** [comment]
thanks for this PR @Natico , though I won't merge this PR into the main branch for the reasons I list here: https://github.com/fullcalendar/fullcalendar/issues/1813#issuecomment-281620201

basically, this is blocked on momentjs adding support for multiple calendar systems. i'd rather do it that way than rely on moment-jalaali, which is essentially a monkeypatched version of moment.

**Comment by arshaw** [comment]
thank you for this PR @Natico. i've done some more research, and the way I want to eventually implement this is described [in this comment](https://github.com/fullcalendar/fullcalendar/issues/1813#issuecomment-652600319)

**Pull request closed without merging**
