### PR TITLE
list view custom columns

### PR DESCRIPTION
**Pull request by BoLaMN**
implements #3422

```{
  listColumns: [
    [
      'Column 1', // Column Header (gets wrapped in <td>)
      'title' // Column Body (eventDef.title) (gets wrapped in <td>)
    ],
    [
      (dayDate, view) => // Column Header (same as Column 1 header)
        `<td class="fc-widget-header">
          <span class="fc-list-heading-main">
            Column 2
          </span>
        </td>`,
      (eventDef, view) => // Column Body (same as Column 1 body)
        `<td class="fc-list-item-column fc-widget-content">
          ${eventDef.title}
        </td>`
    ]
  ]
}```

### CODE REVIEW

**Comment by arshaw** [comment]
This is a nice minimalistic implementation based off the v4 codebase, so I'll leave it open for others to discover, but I plan to eventually implement this as a premium feature that's based off of the table-cell system that resource-timeline uses (https://fullcalendar.io/docs/resourceAreaColumns)

**Comment by BoLaMN** [comment]
I’ve updated the 3 features that I’ve added pull requests to v5 just haven’t had time to split them out and update the individual prs, plus not really sure how todo the options parsing correctly in typescript so it’s just set as ‘any’ atm which probably isn’t good enough for a pr anyhow

**Comment by BoLaMN** [comment]
https://github.com/fullcalendar/fullcalendar/compare/master...BoLaMN:listview-nowindicator-customcolumns is the code i wrote for v5 list custom columns and now indicator rendering.

**Comment by laoneo** [comment]
Nice one, would love to have this in the ordinary list.

**Comment by laoneo** [comment]
@arshaw why did you close this?

**Comment by arshaw** [comment]
I do no know! I changed the default branch name on this repo and might have automatically triggered it. This doesn't seem to have affected other PRs. Who knows. reopening it.

**Comment by arshaw** [comment]
Turns out I can't reopen it. The base branch of this PR is stuck on the nonexistent `master` branch. Could you create a new PR against `main` please?

**Pull request closed without merging**
