### PR TITLE
Added Bengali support

### PR DESCRIPTION
**Pull request by codeshah**
I am not sure about the `allDayHtml`. So left it as it is. If you can explain, then I will correct it too.

### CODE REVIEW

**Comment by arshaw** [comment]
I was wondering about that. It's the text that goes here:
screen shot 2016-11-17 at 12 46 29 am

**Comment by arshaw** [comment]
is that enough information for you to be able to provide a good translation for it?

**Comment by codeshah** [comment]
Thank you for the clarification @arshaw 😃
I have updated translated that string. Please merge if everything seems okay to you.
My twitter username is "codeshah" 😉

**Comment by arshaw** [comment]
thanks!

**Comment by arshaw** [comment]
I have merged theses changes into the `next-release` branch, however, in order for translations to be correctly compiled, there needs to be a jquery-ui translations file available, and there is not:
https://github.com/jquery/jquery-ui/tree/master/ui/i18n

I eventually want to make fullcalendar translations independent from jquery-ui, but that's another project I'll undertake in the future.

**Pull request merged**
